services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: quiz_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - quiz_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  # Backend API (NestJS)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: production
    container_name: quiz_backend
    restart: unless-stopped
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      JWT_SECRET: ${JWT_SECRET}
      FRONTEND_URL: ${FRONTEND_URL}
      BACKEND_URL: ${BACKEND_URL}
      CORS_ORIGINS: ${FRONTEND_URL},${BACKEND_URL}
      DOMAIN_NAME: ${DOMAIN_NAME}
      PROTOCOL: ${PROTOCOL}
    ports:
      - "${PORT}:3001"
    volumes:
      - ./backend/uploads:/app/uploads
      - ./logs/backend:/app/logs
    networks:
      - quiz_network
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/quiz/questions"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Frontend (React)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: quiz_frontend
    restart: unless-stopped
    environment:
      REACT_APP_API_URL: ${BACKEND_URL}/api
      REACT_APP_BACKEND_URL: ${BACKEND_URL}
      REACT_APP_FRONTEND_URL: ${FRONTEND_URL}
      REACT_APP_DOMAIN: ${DOMAIN_NAME}
      REACT_APP_PROTOCOL: ${PROTOCOL}
    ports:
      - "3000:80"
    networks:
      - quiz_network
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2
    container_name: quiz_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PMA_ABSOLUTE_URI: ${PROTOCOL}://${DOMAIN_NAME}:8082/
    ports:
      - "8082:80"
    networks:
      - quiz_network
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data:
    driver: local

networks:
  quiz_network:
    driver: bridge