services:
  mysql:
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-strong-root-password-change-this}
      MYSQL_PASSWORD: ${DB_PASSWORD:-strong-password-change-this}
    volumes:
      - mysql_prod_data:/var/lib/mysql

  backend:
    environment:
      NODE_ENV: production
      JWT_SECRET: ${JWT_SECRET:-change-this-in-production}
      DB_PASSWORD: ${DB_PASSWORD:-strong-password-change-this}
    restart: always

  frontend:
    environment:
      REACT_APP_API_URL: ${REACT_APP_API_URL:-http://localhost:3001/api}
    restart: always

  # Add reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: quiz_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
    networks:
      - quiz-network
    restart: always

volumes:
  mysql_prod_data: